### ISSUE TITLE
An question about  nestedCoalescent.py

### ISSUE THREAD

**Issue by redddlion** [PoonLab/cophylo#1] opened 2020-07-14 21:56 UTC
Hi,
I'm new to cophylogeny and I'm trying to generate some simulated cophylogenetic trees by the script, but I don't know how the simulated parasites tips match to the hosts tips. Could you please give me some ideas?
Thank you!

**Comment by ArtPoon** [comment] 2020-07-14 22:01
Hi @redddlion - thanks for your interest and feedback!  Can you please provide some basic information on your operating system, version of Python, and the command line invocation you've tried?

**Comment by ArtPoon** [comment] 2020-07-14 22:18
Here is a quick example, launched from within the `scripts` directory:
```console
art@Kestrel:~/git/cophylo/scripts$ python nestedCoalescent.py ../data/1.nwk 0.01 0.0001 0.9 include.nwk exclude.nwk
art@Kestrel:~/git/cophylo/scripts$ cat include.nwk
((((Noth1.1_H_P:1e-08,(Mie_H_P:0.00120333,Toya_H_P:9e-08)Mie_H_P_Toya_H_P:0.00120369)Noth1.1_H_P_Mie_H_P_Toya_H_P:1e-08,((Noth1.3_H_P:1e-08,Noth1_H_P:1e-08)Noth1.3_H_P_Noth1_H_P:1e-08,(Noth1.2_H_P:1e-08,(Noth2.1_H_P:1e-08,Noth2_H_P:1e-08)Noth2.1_H_P_Noth2_H_P:0.00120193)Noth1.2_H_P_Noth2.1_H_P_Noth2_H_P:6e-08)Noth1.3_H_P_Noth1_H_P_Noth1.2_H_P_Noth2.1_H_P_Noth2_H_P:7e-08)Noth1.1_H_P_Mie_H_P_Toya_H_P_Noth1.3_H_P_Noth1_H_P_Noth1.2_H_P_Noth2.1_H_P_Noth2_H_P:0.00901939,(((Kuma_H_P:0.00361258,Tsushi_H_P:0.00119503)Kuma_H_P_Tsushi_H_P:6e-08,(Fuku_H_P:0.00119548,Kago_H_P:0.00361895)Fuku_H_P_Kago_H_P:6e-08)Kuma_H_P_Tsushi_H_P_Fuku_H_P_Kago_H_P:0.00365362,(Kuchi_H_P:1e-08,Yaku_H_P:0.00119261)Kuchi_H_P_Yaku_H_P:0.00496018)Kuma_H_P_Tsushi_H_P_Fuku_H_P_Kago_H_P_Kuchi_H_P_Yaku_H_P:0.00632683)Noth1.1_H_P_Mie_H_P_Toya_H_P_Noth1.3_H_P_Noth1_H_P_Noth1.2_H_P_Noth2.1_H_P_Noth2_H_P_Kuma_H_P_Tsushi_H_P_Fuku_H_P_Kago_H_P_Kuchi_H_P_Yaku_H_P:0.00115194,Taiwan_H_P:0.0147514);
```

Let's focus on the first tip label, `Noth1.1_H_P`.  First let's look at the original host tree (Sika deer):
```console
art@Kestrel:~/git/cophylo/scripts$ cat ../data/1.nwk
((((Noth1.1_H:1.0000000001675335E-8,(Mie_H:0.001203329999999999,Toya_H:9.000000000120023E-8):0.0012036900000000003):1.0000000001675335E-8,((Noth1.3_H:1.0000000001675335E-8,Noth1_H:1.0000000001675335E-8):1.0000000001675335E-8,(Noth1.2_H:1.0000000001675335E-8,(Noth2.1_H:1.0000000001675335E-8,Noth2_H:1.0000000001675335E-8):0.0012019300000000004):5.999999999964367E-8):7.000000000131901E-8):0.009019390000000002,(((Kuma_H:0.003612579999999997,Tsushi_H:0.0011950299999999997):6.000000000311312E-8,(Fuku_H:0.0011954799999999988,Kago_H:0.0036189499999999993):6.000000000311312E-8):0.0036536199999999963,(Kuchi_H:1.0000000001675335E-8,Yaku_H:0.0011926100000000002):0.0049601800000000015):0.0063268299999999986):0.0011519350000000015,Taiwan_H:0.014751394999999999);
```

The `_P` suffix in the output tree `include.nwk` indicates that the tip represents a pathogen sequence that was sampled in the host `Noth1.1_H` (we used the suffix `_H` to indicate that the latter is a host sequence).

Now let's examine the internal node label `Noth1.1_H_P_Mie_H_P_Toya_H_P`.  This indicates that the corresponding node is ancestral to the three tips `Noth1.1_H_P`, `Mie_H_P` and `Toya_H_P`.  

For more details I'm going to loop in @mavino who was the first author.

**Comment by redddlion** [comment] 2020-07-14 22:32
Thank your reply! I think I understand it!

**Comment by ArtPoon** [comment] 2020-07-14 22:35
Okay, feel free to post here again if you have any other questions - otherwise please close the issue :)

**Comment by redddlion** [comment] 2020-07-14 22:42
Sorry, that's my first time using issue on github. I will close this issue once I'm sure I don't have other question.

**Comment by ArtPoon** [comment] 2020-07-14 23:04
That's the right way to go about it, in my opinion -- only close the issue if you are sure the problem is resolved, and if there are no subsequent problems that are directly related to this one!

**Closed as completed** 2020-07-14 23:48 UTC
